version: "3.8"  # Adjust if needed

services:
  app:
    platform: linux/amd64
    build: .
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - .:/src  # Mount the app directory from the host for code changes
    environment:
      - PYTHONUNBUFFERED=1  # Fix potential buffering issues (optional)
    command: ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  app_data:  # Optional volume for persistent data (e.g., databases)
